dist: trusty
sudo: require
language: cpp
compiler: gcc

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - openssl
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cmake --version
  - wget https://curl.haxx.se/download/curl-7.59.0.tar.gz
  - tar xf curl-7.59.0.tar.gz
  - cd curl-7.59.0
  - sudo ./configure --disable-shared --enable-static -disable-ldap --disable-sspi --with-ssl --prefix=$HOME
  - sudo make && make install
  - cd ..
  - sudo cp -r $HOME/lib/* lib/
  - sudo cp -r $HOME/include/* include/
  - sudo rm -rf $HOME/bin $HOME/lib $HOME/include curl-7.59.*
  - mkdir build 
  - cd build
  - cmake .. && make
